baseURL = "https://pradyunsg.me/"
title = "Pradyun Gedam"
theme = "PaperMod"
env = "production"

# Infer my posts' dates from filename, like Jekyll
[frontmatter]
date = [":filename", ":default"]
publishDate = [":filename", ":default"]

# Use the same URL structure as my Jekyll blog
[permalinks]
blog = "blog/:year/:month/:day/:slug/"

[params]
defaultTheme = "auto"
showReadingTime = true
showPostNavLinks = true
showCodeCopyButtons = true

# Shown on the home page
socialIcons = [
  { name = "github", url = "https://github.com/pradyunsg" },
  { name = "mastodon", url = "https://mastodon.social/@pradyunsg" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/1931274/pradyunsg" },
  { name = "linkedin", url = "https://www.linkedin.com/in/pradyunsg/" },
  { name = "Python Discourse", url = "https://discuss.python.org/u/pradyunsg/summary" },
  { name = "gitlab", url = "https://gitlab.com/pradyunsg" },
  { name = "keybase", url = "https://www.keybase.io/pradyunsg" },
  { name = "reddit", url = "https://www.reddit.com/user/pradyunsg" },
  { name = "twitter", url = "https://twitter.com/pradyunsg" },
  # { name = "hackerrank", url = "https://www.hackerrank.com/profile/Pradyun"},
]

# Configure the home page
[params.profileMode]
enabled = true # I override the index_profile.html file.

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "about"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "blog"
name = "blog"
title = "Blog"
url = "/blog/"

# Allow HTML in my content pages.
[markup.goldmark.renderer]
unsafe = true
